Update rpc_hsusb.h
the compile error in error: 
'hsusb_chg_vbus_draw' undeclared here (not in a function)
arch/arm/mach-msm/board-msm7x27.c:431: error: 'hsusb_chg_connected' undeclared here (not in a function)
arch/arm/mach-msm/board-msm7x27.c:432: error: 'hsusb_chg_init' undeclared here (not in a function)
is caused by extern symbol references, and thus
this is an attempt to solve those, the functions are declared with extern